prgrms-be-devcourse/BE-02-Slack

src/main/java/com/prgrms/be02slack/Application.java
src/main/java/com/prgrms/be02slack/common/entity/BaseTime.java
src/main/java/com/prgrms/be02slack/workspace/entity/Workspace.java

1. DB에서 Autoincrement된 id값을 해싱한값을 워크스페이스 ID를 나타내는 외부 URL 로 활용하는게 어떨까요, 논의가 필요해 보입니다
-  autoincrement된 값을 URL에 그대로 사용한다면 악의적인 사용자가 임의로 예측하여 워크스페이스에 접근을 시도할수 있을 것으로 보입니다. 
- UUID 를 사용하는 대안이 있는데 URL 이 너무 길어집니다
2. BaseTime 구현에 따른 Application.java @EnableJpaAuditing 어노테이션을 추가하였습니다

:sparkles: XS2-56 Workspace 엔티티 구현 및 BaseTime 엔티티 구현 입니다

---

src/main/resources/application.yaml

개발시 테스트에 사용할 H2 DB와 
JPA 설정 yaml 파일 작성해봤습니다.
추가, 삭제, 수정할 부분 있으면 말씀해주시면 감사하겠습니다.

XS2-106 초기 yaml 작성

---

src/main/java/com/prgrms/be02slack/channel/controller/ChannelApiController.java
src/main/java/com/prgrms/be02slack/channel/entity/Channel.java
src/main/java/com/prgrms/be02slack/channel/service/ChannelService.java
src/main/java/com/prgrms/be02slack/channel/service/DefaultChannelService.java

다음 내용을 구현하였습니다! 
잘못되었거나 추가되어야 할 부분 리뷰 부탁드립니다 🦔
* Channel 엔티티에서 각 필드들의 속성들은 Slack 채널 생성 창을 참조하여 구현하였습니다. 
* 이름: NOT NULL, 최소 1글자, 최대 80글자
* 설명: NULL, 최대 글자 허용 X
* 비공개 여부: NOT NULL 
* 현재 아직 Member 엔티티가 구현되지 않아 Channel 엔티티에서 Member 엔티티와의 연관관계는 구현하지 않았습니다. 
* 추후 동일 워크스페이스 내 사용자 이름 중복 확인, 동일 워크스페이스 내 다른 채널 이름과 중복 확인 validation이 추가 되어야 할 것 같습니다.

:sparkles: XS2-78 Channel 엔티티 작성 및 클래스 구조 작성

---

src/main/java/com/prgrms/be02slack/member/controller/MemberApiController.java
src/main/java/com/prgrms/be02slack/member/entity/Member.java
src/main/java/com/prgrms/be02slack/member/entity/Role.java
src/main/java/com/prgrms/be02slack/member/service/DefaultWorkspaceService.java
src/main/java/com/prgrms/be02slack/member/service/MemberService.java

멤버 엔티티와 클래스 구조를 구현해봤습니다.
email : 사용자 email
name : 실제 이름 (1 ~ 80)
displayName : 워크스페이스 표시 이름 (1 ~ 80)
role : 소유자, 일반 멤버 권한
workspace : 워크스페이스 식별자 
- 필드들은 슬랙 api objecttype을 참고했습니다
https://api.slack.com/types/user
- 이름 중복은 체크하지 않는 것 같습니다.
- 추가 구현 해야할 부분
타임존을 어떻게 적용할지 찾아보고 있습니다.

XS2-124 - 멤버 엔티티 구현 및 클래스 구조 작성

---

src/main/java/com/prgrms/be02slack/member/service/MemberService.java
src/main/java/com/prgrms/be02slack/workspace/entity/Workspace.java
src/main/java/com/prgrms/be02slack/workspace/service/DefaultWorkspaceService.java
src/main/java/com/prgrms/be02slack/workspace/service/WorkspaceService.java
src/test/java/com/prgrms/be02slack/workspace/service/DefaultWorkspaceServiceTest.java

첫 로그인(회원가입)시 생성하는 기본 워크스페이스 생성 구현입니다.
MemberService에서 해당 기능을 호출해 처음 생성하는 소유주 멤버를 생성하도록 구현할 예정입니다. 
아래 동그라미 부분입니다.
피드백 주시면 변경사항 반영하겠습니다.

Xs2 60 기본 워크스페이스 생성기능 구현

---

.github/workflows/pull-request.yml
src/main/java/com/prgrms/be02slack/email/service/EmailService.java
src/test/java/com/prgrms/be02slack/email/controller/EmailControllerTest.java

Git flow 를 통해 main branch PR 전 테스트, 코드스타일 검사 를 진행하는 CI  로직을 추가하였습니다.

:wrench: main branch PR 전 테스트, 코드스타일 검사 CI 추가

---

.github/workflows/pull-request.yml

자동 코드 포메팅과 상관없이 너무 많은 경고를 띄우는것 같아 제거하는게 좋을것 같습니다.

:adhesive_bandage: CheckStyle 제거

---

build.gradle
src/main/java/com/prgrms/be02slack/common/configuration/redis/RedisConfig.java
src/main/java/com/prgrms/be02slack/common/configuration/websocket/WebSocketConfig.java
src/main/resources/application.yaml

웹소켓 설정부분 구현입니다. 이후 구현은 다음과 같이 진행될것 같습니다.
- 송신자는 /pub/api/v1/workspace/{workspaceId}/channel/{channelId} 으로 발행 요청을 하면 ChannelController 가 해당 메시지를 받아 처리하도록 구현하고
- 수신자는 /sub/workspace/{workspaceId}/channel/{channelId} 를 구독하고 있다가 메시지가 전달되면 화면에 출력하게 됩니다.
url 은 예시고 변경이 필요하다면 논의 해봐야할것같습니다.

XS2-117 웹소켓 설정 구현(STOMP, Redis)

---

src/main/java/com/prgrms/be02slack/common/exception/ExceptionController.java

제가 하영님이 추가하신 코드를 PULL 하지 않고 EXCEPTION CONTROLLER 작성 후 머지를 해서 처리되지 않은 코드가 있었습니다. 조심하겠습니다 🙇  
충돌은 없었습니다!

:recycle: XS2-104 ExceptionController 수정

---

src/main/java/com/prgrms/be02slack/member/service/DefaultMemberService.java

서비스레이어중 Transactional 이 빠진부분이 있어서 추가합니다

XS2-158:adhesive_bandage: Transactional 추가

---

src/main/java/com/prgrms/be02slack/message/entity/Message.java

메시지 엔티티 구현입니다 
이슈에 구체적인 내용 올렸습니다
#55

:sparkles: Message 엔티티 구현

---

src/main/java/com/prgrms/be02slack/directmessagechannel/controller/DirectMessageChannelApiController.java
src/main/java/com/prgrms/be02slack/directmessagechannel/entity/DirectMessageChannel.java
src/main/java/com/prgrms/be02slack/directmessagechannel/service/DefaultDirectMessageChannelService.java
src/main/java/com/prgrms/be02slack/directmessagechannel/service/DirectMessageChannelService.java
src/test/java/com/prgrms/be02slack/directmessagechannel/controller/DirectMessageChannelApiControllerTest.java
src/test/java/com/prgrms/be02slack/directmessagechannel/service/DirectMessageChannelServiceTest.java

1. 엔티티 joincolumn 매핑 이름 수정 
```
member_id -> member_id1
member_id -> member_id2
```
2. `@CurrentMember `어노테이션 적용
Controller, Service 프로덕션, 테스트 코드 변경

[XS2-73] DM채널 변경 코드 수정

---

src/main/java/com/prgrms/be02slack/common/configuration/websocket/WebSocketConfig.java
src/main/java/com/prgrms/be02slack/message/controller/MessageWebsocketController.java
src/main/java/com/prgrms/be02slack/message/controller/dto/MessageWebsocketRequest.java
src/main/java/com/prgrms/be02slack/message/controller/dto/MessageWebsocketResponse.java
src/main/java/com/prgrms/be02slack/message/entity/Message.java
src/main/java/com/prgrms/be02slack/message/service/DefaultMessageService.java
src/main/java/com/prgrms/be02slack/message/service/MessageService.java
src/test/java/com/prgrms/be02slack/message/controller/MessageWebsocketControllerTest.java

- 웹소켓을 통해 메시지를 스프링 브로커에 발행하고 브로드캐스팅 하는 컨트롤러를 구현하였습니다.
- 웹소켓 사용으로 인해 통합테스트를 사용하였습니다.(단위테스트 가능한 방법을 찾지못했습니다)

[XS2-72] MessageWebsocketController 구현

---

src/main/java/com/prgrms/be02slack/workspace/controller/WorkspaceApiController.java
src/main/java/com/prgrms/be02slack/workspace/controller/dto/WorkspaceResponse.java
src/main/java/com/prgrms/be02slack/workspace/repository/WorkspaceRepository.java
src/main/java/com/prgrms/be02slack/workspace/service/DefaultWorkspaceService.java
src/main/java/com/prgrms/be02slack/workspace/service/WorkspaceService.java
src/test/java/com/prgrms/be02slack/workspace/service/DefaultWorkspaceServiceTest.java

- 이메일은 통한 워크스페이스 조회 기능을 구현하였습니다.
- 컨트롤러에 응답상태코드를 명시적으로 작성하였습니다.
- apiController 테스트에서 NestedServletException이 발생하여서 작성 못하였습니다. (해결 방안 찾지 못함)

[XS2-144] 이메일을 통한 워크스페이스 조회 기능 구현

---

src/main/java/com/prgrms/be02slack/channel/controller/ChannelApiController.java
src/main/java/com/prgrms/be02slack/channel/service/ChannelService.java
src/main/java/com/prgrms/be02slack/channel/service/DefaultChannelService.java
src/test/java/com/prgrms/be02slack/channel/controller/ChannelApiControllerTest.java
src/test/java/com/prgrms/be02slack/channel/service/DefaultChannelServiceTest.java

* 채널 구독 취소 기능을 구현했습니다.
* 다음 pr에는 "채널 api 시큐리티 적용"을 올릴 거 같습니다~

[XS2-66] 채널 구독 취소 기능

---

src/main/java/com/prgrms/be02slack/common/configuration/security/SecurityConfig.java
src/test/java/com/prgrms/be02slack/channel/controller/ChannelApiControllerTest.java

* ChannelApiController 에 시큐리티 적용했습니다!

[XS2-163] ChannelApiController 에 시큐리티 적용

---

src/main/java/com/prgrms/be02slack/member/controller/MemberApiController.java
src/main/java/com/prgrms/be02slack/member/entity/Member.java
src/main/java/com/prgrms/be02slack/member/repository/MemberRepository.java
src/main/java/com/prgrms/be02slack/member/service/DefaultMemberService.java
src/main/java/com/prgrms/be02slack/member/service/MemberService.java
src/test/java/com/prgrms/be02slack/member/controller/MemberControllerTest.java
src/test/java/com/prgrms/be02slack/member/service/DefaultMemberServiceTest.java

- 인코딩된 워크스페이스 아이디를 이용해 멤버를 조회하는 기능입니다.
단순히 기능적인 부분만 구현했는데 시큐리티를 통해서 호출자의 workspace 소속 여부를 확인하는 기능이 추가되어야 될 거 같습니다!

[XS2 143] 워크스페이스 아이디를 통한 멤버 조회 기능 구현

---

src/main/java/com/prgrms/be02slack/channel/entity/Channel.java
src/main/java/com/prgrms/be02slack/channel/service/DefaultChannelService.java
src/main/java/com/prgrms/be02slack/common/enums/EntityIdType.java
src/main/java/com/prgrms/be02slack/common/util/IdEncoder.java
src/main/java/com/prgrms/be02slack/directmessagechannel/entity/DirectMessageChannel.java
src/main/java/com/prgrms/be02slack/directmessagechannel/service/DefaultDirectMessageChannelService.java
src/main/java/com/prgrms/be02slack/member/entity/Member.java
src/main/java/com/prgrms/be02slack/member/service/DefaultMemberService.java
src/main/java/com/prgrms/be02slack/workspace/entity/Workspace.java
src/test/java/com/prgrms/be02slack/channel/service/DefaultChannelServiceTest.java
src/test/java/com/prgrms/be02slack/common/util/IdEncoderTest.java
src/test/java/com/prgrms/be02slack/directmessagechannel/service/DirectMessageChannelServiceTest.java
src/test/java/com/prgrms/be02slack/member/service/DefaultMemberServiceTest.java

#55  해당 이슈 내용에 대한 IdEncoder 수정입니다.
해시값 앞에 각 엔티티별 문자를 넣어줬습니다.
`WorkSpace : T`
`Member : M`
`Channel : C`
`DMChannel D`

[XS2-71] IdEncoder 수정

---

src/main/java/com/prgrms/be02slack/member/entity/Member.java
src/main/java/com/prgrms/be02slack/member/exception/ErrorMessage.java
src/main/java/com/prgrms/be02slack/member/service/DefaultMemberService.java
src/main/java/com/prgrms/be02slack/subscribeInfo/repository/SubscribeInfoRepository.java
src/main/java/com/prgrms/be02slack/subscribeInfo/service/DefaultSubscribeInfoService.java
src/main/java/com/prgrms/be02slack/subscribeInfo/service/SubscribeInfoService.java
src/test/java/com/prgrms/be02slack/member/service/DefaultMemberServiceTest.java
src/test/java/com/prgrms/be02slack/subscribeInfo/service/DefaultSubscribeInfoServiceTest.java

* 채널 내 멤버 조회 기능 Service 구현입니다.

[XS2-68] 채널 내 멤버 조회 기능 Service 구현

---

src/main/java/com/prgrms/be02slack/common/enums/EntityIdType.java
src/main/java/com/prgrms/be02slack/member/entity/Member.java
src/main/java/com/prgrms/be02slack/message/entity/Message.java
src/test/java/com/prgrms/be02slack/common/util/IdEncoderTest.java
src/test/java/com/prgrms/be02slack/member/service/DefaultMemberServiceTest.java

Entity ID Encoder 변경
`MEMBER -> USER`
`MESSAGE` 추가

[XS2-167] EntityIdType MEMBER-> USER, MESSAGE 추가
